apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: tutorial-frontend
  name: tutorial-frontend
spec:
  port:
    targetPort: 3000
  to:
    kind: Service
    name: tutorial-frontend
    weight: 100
